services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - ./config.json:/app/config.json
      - ./.env:/app/.env
  db:
    image: postgres:latest
    container_name: cloudDB
    environment:
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
      POSTGRES_DB: cloudDB
    volumes:
      - cloudata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
volumes:
  cloudata: