services:
  db:
    image: postgres:latest
    container_name: cloudDB
    environment:
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
      POSTGRES_DB: cloudDB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"